Repository aau-p9s/Autoscaler, pull requests merged in 2025-03, with the labels that each got.

#91 Feat/add enable autoscaling and add deployment to UI
  Autoscaler.Api/App/package-lock.json
  Autoscaler.Api/App/package.json
  Autoscaler.Api/App/src/custom.css
  Autoscaler.Api/App/src/index.js
  Autoscaler.Api/App/src/service/[id]/ServicePage.css
  Autoscaler.Api/App/src/service/[id]/service.jsx
  Autoscaler.Api/Controllers/PublicController.cs
  Autoscaler.Api/Program.cs
  Autoscaler.DbUp/Scripts/0004-SettingsTable.sql
  Autoscaler.DbUp/Scripts/0005-ServicesTable.sql
  Autoscaler.Persistence/Extensions/ServiceCollectionExtension.cs
  Autoscaler.Persistence/ServicesRepository/ServiceEntity.cs
  Autoscaler.Persistence/ServicesRepository/ServicesRepository.cs
  Autoscaler.Persistence/SettingsRepository/ISettingsRepository.cs
  Autoscaler.Persistence/SettingsRepository/SettingsEntity.cs
  Autoscaler.Persistence/SettingsRepository/SettingsRepository.cs
  Autoscaler.Runner/Runner.cs
  Autoscaler.Tests/RepositoryTests/ForecastRepositoryTests.cs
  Autoscaler.Tests/RepositoryTests/HistoricRepositoryTests.cs
  Autoscaler.Tests/RepositoryTests/ModelRepositoryTests.cs
  Autoscaler.Tests/RepositoryTests/ServicesRepositoryTests.cs
  Autoscaler.Tests/RepositoryTests/SettingsRepositoryTests.cs
  Autoscaler.Tests/SampleTests.cs
Labels: enhancement

#106 Added kubernetes HPA scaling policy
  Autoscaler.Runner/Runner.cs
Labels: enhancement

#112 fixed access to forecaster for deployment
  Autoscaler.Runner/Runner.cs
  Autoscaler.Runner/Services/ForecasterService.cs
Labels: bug

#118 fear: added min/max replica setting
  .github/workflows/api_test.sh
  Autoscaler.Api/App/src/service/[id]/service.jsx
  Autoscaler.DbUp/Scripts/0004-SettingsTable.sql
  Autoscaler.DbUp/Scripts/0006-SeedData.sql
  Autoscaler.Persistence/SettingsRepository/SettingsEntity.cs
  Autoscaler.Persistence/SettingsRepository/SettingsRepository.cs
  Autoscaler.Runner/Runner.cs
Labels: enhancement, Should Have, Small :baby:

#123 feat: added the 10th percentile slowest spin up time calculater
  Autoscaler.Api/DevelopmentData/containers.json
  Autoscaler.Runner/Runner.cs
  Autoscaler.Runner/Services/KubernetesService.cs
Labels: Must Have

#122 Added threshold for when to retrain the model as well as a small refa…
  Autoscaler.Persistence/SettingsRepository/SettingsEntity.cs
  Autoscaler.Runner/Runner.cs
  Autoscaler.Runner/Services/ForecasterService.cs
  Autoscaler.Runner/Services/KubernetesService.cs
Labels: Must Have
